apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb-mysql
  namespace: 
spec:
  replicas: 1
  selector:
    app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
        containers:
        - image: docker.io/mysql:5.7
          imagePullPolicy:  #不使用远程镜像
          name: mysql
          ports:
          - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
