apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    run: webserver
spec:
  type: NodePort
  ports:
    - port: 1316
      targetPort: 1316
      nodePort: 32000
  selector:
    app: webserver
