apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver
  labels: 
    app: webserver
spec:
  replicas: 5 
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: 192.168.239.139:5000/webserver-test:latest 
